/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Karol Miklas (https://sketchfab.com/karolmiklas)
license: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
source: https://sketchfab.com/3d-models/free-1972-datsun-240k-gt-b2303a552b444e5b8637fdf5169b41cb
title: (FREE) 1972 Datsun 240k GT
*/

import { useGLTF } from '@react-three/drei'
import { useLayoutEffect, useRef, useState } from 'react'

export function Model({ color, ...props }) {
  
  const { scene, nodes, materials } = useGLTF('/WBR-comp.glb', { useDraco: true, useMeshopt: true })
  // const { } = useGLTF('/wbr1.glb')
  useLayoutEffect(() => {
    Object.values(nodes).forEach((node) => node.isMesh && (node.receiveShadow = node.castShadow = true))
  }, [nodes, materials])
  return <primitive object={scene} {...props} />
}

useGLTF.preload('/WBR-comp.glb')
